### ISSUE TITLE
Request init by encoder pins

### ISSUE THREAD

**Issue by mariodantas** [RobTillaart/rotaryDecoder#6]
Hellow fellow, nice lib for managing encoders with PCF8574

Is it possible to add a way to "encoder.setpins(2,3)" where 2 and 3 are the pins of a single encoder ?

**Comment by RobTillaart** [comment]
Thanks for the question.
It might take several days to Investigate as I am quite busy.

About the question
Do you mean that you want to have only one encoder on pins 2 and 3. The other pins 0, 1,4-7 are e.g  controlling LEDs?
Do you also want **encoder.setpins(5,1)** so pins can be any group or order?

**Comment by RobTillaart** [comment]
As my questions are not answered in a week time I close this issue. 
Feel free to reopen if needed.
